function img = myImgShow(filename, width, height)
% SHOW IMAGE
% Example:
%   filename = 'C:\SAVE_IMG.TXT';
%   width  = 512
%   height = 512
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/01/28 18:44:09

%% Initialize variables.
startRow = 1;
endRow = inf;

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%3f%4f%4f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
r = dataArray{:, 1};
g = dataArray{:, 2};
b = dataArray{:, 3};
a = dataArray{:, 4};

r = reshape(r, [width, height])';
g = reshape(g, [width, height])';
b = reshape(b, [width, height])';
a = reshape(a, [width, height])';

img = [];
img(:,:,1) = r./255;
img(:,:,2) = g./255;
img(:,:,3) = b./255;
img(:,:,4) = a./255;

figure;
imshow(img(:,:,[1 2 3]));

end
